### ISSUE TITLE
version

### ISSUE THREAD

**Issue by ONElua** [1upus/QuickLaunch_installer_for_PSVita#1]
if you are going to use the updater then you must create a "version" file and use this link
http://devonelua.x10.mx/tools/version2int.php
sample (v1.00)
01
00
result : 16777216

PD: anytime you want to release an update you will have to upload the changes first, then edit the file shared.lua... upload the updated vpk and at the end update the "version" file
remember to edit the sfo, changeinfo and livearea.xmls

**Comment by 1upus** [comment]
Thank you!
