### ISSUE TITLE
Doesn't seems to work on REX units :(

### ISSUE THREAD

**Issue by szczuru** [1upus/QuickLaunch_installer_for_PSVita#3]
This tool doesn't seems to work on REX units (CEX2DEX with SKGleba's Testkit mod patcher). Any ideas how to fix it?

**Comment by 1upus** [comment]
The app don’t run or not install custom data?

**Comment by szczuru** [comment]
App seems to works ok but after restart none of shortcuts are added (even SCE's default). Maybe it's because i'm using debug SceShell? 
SKGeba commented tis issue on reddit:

> Because of DEX Shell ( or TOOL shell if u are using devkit spoof)

**Comment by 1upus** [comment]
Maybe.
Try to use airplain mode, manually backup and delete all data from ur0:shell/whats_new/np/

**Comment by szczuru** [comment]
> Try to use airplain mode, manually backup and delete all data from ur0:shell/whats_new/np/

Not working :(

But i've solved this issue by simply uninstalling testkit mod
https://github.com/Voxel9/Testkit-Installer-Deluxe/releases/

Now everything is working :D
